name = "fparma-mods"
prefix = "fpa"
author = "FP Mod team"
modname ="fp_core"
keyname = "fp_core_v{{version}}"
signame = "fp_core_v{{version}}"
files = [
    "mod.cpp",
    "mod.cpp",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ca.paa",
    "README.md"
]
skip = [
    "ai_danger",
    "difficulty",
    "compositions"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]
reuse_private_key = false
